# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kazesawa フォント: M+ と Source Sans Pro の合成フォント"
description: "Kazesawa (かぜさわ) フォントは、画面での見やすさと適度な情報密度の両立を目指した M+ と Source Sans Pro の合成フォントです。"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kazesawa.github.io" # the base hostname & protocol for your site
github_username: kazesawa

# Build settings
markdown: kramdown

exclude: ["vendor", "Gemfile", "Gemfile.lock", "Makefile"]
